AllCops:
    TargetRubyVersion: 2.3

Metrics/AbcSize:
    Enabled: false

Metrics/BlockLength:
    Enabled: false

Metrics/ClassLength:
    Enabled: false

Metrics/LineLength:
    Enabled: false

Metrics/MethodLength:
    Enabled: false
